version: "3.5"

services:
 api:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "7000:80"
  depends_on:
   - db-server

 db-server:
  image: "mcr.microsoft.com/mssql/server:2022-latest"
  container_name: db-server
  ports:
   - "1433:1433"

  environment:
   SA_PASSWORD: "Testing123"
   ACCEPT_EULA: "Y"